### PR TITLE
button changes

### PR DESCRIPTION
**Pull request by JoeNeedham**

### CODE REVIEW

**Comment by JoeNeedham** [comment]
https://github.com/akshitagupta15june/Moksh/assets/83193580/00467572-a230-4d96-9b7f-cb6332bef1ed

**Review by akshitagupta15june — APPROVED** [review]
Good work!

**Comment by akshitagupta15june** [comment]
please update with current codebase

**Comment by JoeNeedham** [comment]
> please update with current codebase

Should be all set now.

**Pull request merged**
