### PR TITLE
Updated meditation page

### PR DESCRIPTION
**Pull request by ankitjt**
Changes made -

1. Added bootstrap CDN to the page;
2. Updated the navbar as per the index page, also added hover affects on the link and how it will behave on smaller screens;
3. Added new font family to the page (montserrat), if that's not needed I can change to the font which is currently used;
4. Page is responsive across all screen sizes;
5. Added Bootstrap classes where ever required;
6. Moved the id to the div instead of the 'play icon' to make it more aesthetic and user friendly. ( flute music section) i.e. when user clicks anywhere in the div audio gets played instead of explicitly clicking on the play icon;
7. Added hover on the individual flute music section for interaction purposes;
8. Opening more features is a click event instead of hover, as hovering  around edges of the list can abruptly close the dropdown.

Pl review the changes. 

Issue #138 

Thanks.

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
add a screenshot

**Comment by ankitjt** [comment]
image

image

It looks almost identical, either way here are the screenshots. Hope it helps.

**Review by akhil888binoy — APPROVED** [review]

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
good work @ankitjt

**Comment by ankitjt** [comment]
Hey Akshita,

This was my first PR. 

Seeing your feedback is such a confidence boost for me.

Thank you for letting me work on this, means a lot.

If you have the time I would really like to talk about few changes that we can implement on the project. 

Thanks anyways.

P.S. I posted an comment on issue #148 which is regarding the Blog page. Please see it.

**Comment by akshitagupta15june** [comment]
You really did a great work in meditation page! and congrats on your first pull request.

Yes I am planning for a online meetup soon to discuss about the project also please join the discord channel and send me a dm I would like to give you a surprise giveaway of Github stickers for your contributions!!

**Pull request merged**
