### PR TITLE
Feat: Improve the 'power of shlokas' page

### PR DESCRIPTION
**Pull request by Viveksati5143**
Closes: #1079

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
is this completed?
Please provide screenshots, along with responsiveness ss

**Comment by Viveksati5143** [comment]
> is this completed? Please provide screenshots, along with responsiveness ss

I asked you to suggest background image I'm still waiting or should I add by myself?

**Comment by akshitagupta15june** [comment]
take reference from iskcon page

**Comment by Viveksati5143** [comment]
Ok sure.

**Comment by Viveksati5143** [comment]
Also, what else can i add to make it level 3? 
Any suggestions @akshitagupta15june ?

**Comment by akshitagupta15june** [comment]
As the changes are in existing feature then it wouldn't be level 3

**Comment by akshitagupta15june** [comment]
let me know if you are done with it

**Comment by Viveksati5143** [comment]
> As the changes are in existing feature then it wouldn't be level 3



> let me know if you are done with it

ok sure, you can review it then
I have made many changes as of level 2 then

**Comment by akshitagupta15june** [comment]
Add screenshots please

**Review by Viveksati5143 — COMMENTED** [review]
Responsiveness:
image
image
image
image

**Comment by Viveksati5143** [comment]
> Add screenshots please

Fixed code, typos and improved readability of overall code:
image


Linked missing stylesheet:
image

**Review by akshitagupta15june — APPROVED** [review]
Good work!

**Pull request merged**
