### PR TITLE
"About ISKCON" Added in About Section #222

### PR DESCRIPTION
**Pull request by rayarka26**
Please check #gssoc23

### CODE REVIEW

**Comment by rayarka26** [comment]
Screenshot (30)

**Comment by rayarka26** [comment]
Screenshot (30)

**Comment by Rakesh9100** [comment]
Pls mention the issue number this PR closes in the description.
Reviewed, Nice work.

Can be merged @akshitagupta15june

**Comment by rayarka26** [comment]
Issue #222
'Include a "About ISKCON" part in About section and their achievements'
@akshitagupta15june

**Comment by rayarka26** [comment]
@akshitagupta15june please check and merge it #gssoc23

**Comment by rayarka26** [comment]
updated please check
Screenshot (31)

**Comment by rayarka26** [comment]
@akshitagupta15june please check

**Comment by rayarka26** [comment]
Added in ISKCON Events part
Screenshot (31)

**Comment by rayarka26** [comment]
Final done please check and merge

**Pull request closed without merging**
