### PR TITLE
tweet new quote functionality added

### PR DESCRIPTION
**Pull request by swapnilgarg7**
User is now able to tweet the newly generated quotes as well (fixed [issue#14](https://github.com/akshitagupta15june/Moksh/issues/14))

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
can you give a video of showing whether it generating new one and posting newly generated issue to verify

**Comment by swapnilgarg7** [comment]
Screenshot 2023-04-09 at 8 58 14 PM
Screenshot 2023-04-09 at 8 58 47 PM
As you can see in the above screenshots, the new quotes are also able to be tweeted now

**Comment by swapnilgarg7** [comment]
In this PR itself, I have also added a commit of improving the rejuvenate section by adding scroll horizontal feature
Screenshot 2023-04-09 at 8 55 30 PM

**Review by akshitagupta15june — APPROVED** [review]
Good work!

**Pull request merged**
