### PR TITLE
add hover effect to navbar

### LINKED ISSUE #992: Add Hover Effect to Navbar Buttons On Augmented Reality Meditation Page
The navbar buttons on Augmented Reality Meditation page lack any visual feedback when users hover over them, which can lead to a less intuitive user experience.
Screenshot (29)

### PR DESCRIPTION
**Pull request by Aditi-P22**
Description
Added hover effect to navbar buttons on Augmented Reality Meditation page.

Issue number #992 
Screenshot (33)

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
add a screenshot and issue number

**Comment by Aditi-P22** [comment]
Issue number #992 

Screenshot (33)

**Comment by Aditi-P22** [comment]
Issue number #992 
Screenshot (34)

**Comment by akshitagupta15june** [comment]
Hey you were not assigned this issue so I can't merge it

**Pull request closed without merging**
