### PR TITLE
Have enhanced the features section

### PR DESCRIPTION
**Pull request by karthiknadar1204**

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
please provide a picture of the enhancement

**Comment by karthiknadar1204** [comment]
@a
Screenshot 2023-04-09 at 7 43 18 PM
kshitagupta15june ,have shared the picture in the issue section

**Comment by karthiknadar1204** [comment]
@akshitagupta15june ,updated the changes with image.

Thank you

**Comment by karthiknadar1204** [comment]
Should i submit another pr

**Review by akshitagupta15june — APPROVED** [review]
Good work!

**Pull request merged**
