### PR TITLE
"Power of Sloks" added in navbar

### PR DESCRIPTION
**Pull request by rayarka26**
Issue Number #223

### CODE REVIEW

**Comment by rayarka26** [comment]
Screenshot (38)

**Comment by rayarka26** [comment]
@akshitagupta15june please check
#gssoc23

**Review by akshitagupta15june — APPROVED** [review]
hey i would suggest you to add these in the shlok.html by creating small cards and less description we are focusing on bhagwadgita shloks so i would suggest to add the cards below the shlok generator means just above footer

**Comment by akshitagupta15june** [comment]
just add a importance of shloks section in navbar of shlok html file

**Comment by rayarka26** [comment]
Screenshot (39)
Screenshot (40)

**Comment by rayarka26** [comment]
I hope its right @akshitagupta15june

**Review by akshitagupta15june — APPROVED** [review]
great work!!

**Pull request merged**
