### PR TITLE
added a new button 

### PR DESCRIPTION
**Pull request by debdutta04**
fixes issues #1302 
Screenshot 2023-08-10 223142

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Can u provide the working of that button like a screenshot or a video

**Comment by debdutta04** [comment]
https://github.com/akshitagupta15june/Moksh/assets/111264897/76a30ee5-9bb1-4336-b76f-dbd1a7c93a78

**Comment by debdutta04** [comment]
@akshitagupta15june mam please check it out

**Comment by akshitagupta15june** [comment]
Hey there are 2prs why not one can u close that background music one

**Comment by debdutta04** [comment]
Sure mam

**Comment by akshitagupta15june** [comment]
hey on clicking that button can song be paused and again played means the ui of button changes?

**Comment by debdutta04** [comment]
Yes

**Review by akshitagupta15june — APPROVED** [review]

**Pull request merged**
