### PR TITLE
Added more questions and answers

### PR DESCRIPTION
**Pull request by mangalamraj**
Added More Questions and Answers according to the provided document
Here are the screenshots:-
Screenshot 2023-10-11 at 11 06 43 PM
Screenshot 2023-10-11 at 11 06 34 PM

### CODE REVIEW

**Comment by mangalamraj** [comment]
but @Viveksati5143 two CodeQL tests are failing.

**Comment by mangalamraj** [comment]
> but @Viveksati5143 two CodeQL tests are failing.

??????

**Comment by mangalamraj** [comment]
> but @Viveksati5143 two CodeQL tests are failing.

??????

**Comment by akshitagupta15june** [comment]
Were u assigned this issue?

**Comment by mangalamraj** [comment]
> Were u assigned this issue?

no, but i saw this issue was opened for a while so i solved it

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
please synk you codebase
update it with recent changes

**Comment by mangalamraj** [comment]
i have synced my main branch but to do that with this branch?

**Comment by mangalamraj** [comment]
@akshitagupta15june I have to make a pull request with updated branch i think

**Review by Viveksati5143 — COMMENTED** [review]
Sync changes in your `mangalamraj:MoreQuestions` branch

**Pull request closed without merging**
