### PR TITLE
Improved UI of Footer for "Read The Shlok" page

### PR DESCRIPTION
**Pull request by ashish-khankari**

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
can u give a screenshot of implementation

**Comment by ashish-khankari** [comment]
Screenshot (270)

**Comment by ashish-khankari** [comment]
Screenshot (271)
At First You could not move the shlokas, now you can freely move the shlokas

**Comment by ashish-khankari** [comment]
Ok, I will make relevant changes

**Comment by ashish-khankari** [comment]
check the above image its is perfect, It is distorting the new quote button and twitter

**Comment by akshitagupta15june** [comment]
ok

**Review by akshitagupta15june — APPROVED** [review]
Thanks

**Pull request merged**
