### PR TITLE
updated the new logo of twitter

### PR DESCRIPTION
**Pull request by Mandeep-009**

### CODE REVIEW

**Comment by Mandeep-009** [comment]
It fixes issue #1284

**Comment by akshitagupta15june** [comment]
please provide a screenshot

**Comment by Mandeep-009** [comment]
Screenshot from 2023-09-25 17-04-04

this is the new logo

**Comment by Mandeep-009** [comment]
Screenshot from 2023-09-25 17-04-01

this is the screenshot while hovering on the logo

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
Thanks

**Pull request merged**
