### PR TITLE
Issue #1218 Resolved. Completely restructured the html and css files

### PR DESCRIPTION
**Pull request by ArunMaramraj**
@akshitagupta15june I had to completely restructre the html page because the positioning of the pre existing file was distorted. I  also deleted the scroll.js file because it is unnecessary. It was supposed to be used for navbar content but I used the navbar in commonScript.js file. This is how it looks finally.

https://github.com/akshitagupta15june/Moksh/assets/121447227/1237d3bf-9290-4ee3-91b3-251d571b198a

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]
Great work!

**Comment by akshitagupta15june** [comment]
it is still facing some issues can u see to it? whole data is not displayed

**Comment by ArunMaramraj** [comment]
@akshitagupta15june are you referring to the audio part?

**Comment by akshitagupta15june** [comment]
image
no please see this

**Comment by ArunMaramraj** [comment]
@akshitagupta15june. This is how it appears on my screen. This was recorded just now.  There might have been a change in codebase. This is how my version looks like. Should i create another PR with the changes or can you revert this PR so that i can once again make the changes in files?

https://github.com/akshitagupta15june/Moksh/assets/121447227/26324bd5-0df0-4ea6-b757-027a7623a375

**Comment by akshitagupta15june** [comment]
yes when its added here it becomes distorted

**Comment by ArunMaramraj** [comment]
@akshitagupta15june do you want me to create a new PR again, this time without any labels? Can you just check if it works or it's still distorted?

**Pull request merged**
