### PR TITLE
Issue-No-#1001 Resolved - [STYLE CHANGE] Fix the footer on the shlok page .

### PR DESCRIPTION
**Pull request by gauravsingh1281**
#1001

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
add a screenshot please also add a screenshot for showing its responsiveness

**Comment by akshitagupta15june** [comment]
@gauravsingh1281

**Comment by gauravsingh1281** [comment]
Screenshot ----------
Screenshot 2023-07-08 002239
Screenshot 2023-07-08 002549
Screenshot 2023-07-08 003355
Screenshot 2023-07-08 003430

**Comment by akshitagupta15june** [comment]
Hey the shlok part is hidden by the footer
Can u correct that and give proper spacing

**Comment by gauravsingh1281** [comment]
ok i will try but sirf shlok hi h content me pehle jo content tha wo apne hta diya isliye shyd ye issue aarhi

**Comment by gauravsingh1281** [comment]
ok i will try

**Comment by akshitagupta15june** [comment]
yes please!

**Comment by gauravsingh1281** [comment]
Updated Pr #1005

**Comment by gauravsingh1281** [comment]
Updated Pull Request #1038

**Pull request closed without merging**
