### PR TITLE
fixed font size in mobile view

### LINKED ISSUE #1716: Issue/Suggestion
Decreasing font size and doing other changes to make this page look beautiful 

**Issue and Steps to Reproduce:**
Font size not looking good in mobile view 

**Screenshots:**

**Expected:**

Font size should decrease in mobile view so that it look good

**Actual:**
Font size is not looking good

**Additional Details:**
Please assign this issue to me under gssoc @akshitagupta15june

### PR DESCRIPTION
**Pull request by dhairyagothi**
## Related Issue

Closes: #1716 

## Description

fixed font size in mobile view

## Screenshots
image

## Checklist 

- [X] My code adheres to the established style guidelines of the project.
- [X] I have included comments in areas that may be difficult to understand.
- [X] My changes have not introduced any new warnings.
- [X] I have conducted a self-review of my code.

@akshitagupta15june please merge my PR with Gssoc label

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@akshitagupta15june please merge my PR with Gssoc label

**Comment by dhairyagothi** [comment]
Please merge the PR @akshitagupta15june

**Comment by dhairyagothi** [comment]
merge it under gssoc @akshitagupta15june

**Review by akshitagupta15june — APPROVED** [review]

**Comment by dhairyagothi** [comment]
@akshitagupta15june please assign me

**Pull request merged**
