### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rohansx**
Updated the readme file

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Images have been removed

**Comment by rohansx** [comment]
Screenshot_2023-04-19-10-13-13-53_e4424258c8b8649f6e67d283a50a2cbc
Images are not visible. The link is broken. So I commented out the images

**Comment by akshitagupta15june** [comment]
all images are visible

**Comment by rohansx** [comment]
As you can see the screenshot there is no image visible. I tried checking from other device too. This screenshot is taken from other device.
Do you want to me to keep as it is ?

**Comment by akshitagupta15june** [comment]
image
all images are visible

**Comment by rohansx** [comment]
Ok.. it is visible now.
Please check it again

**Review by akshitagupta15june — APPROVED** [review]

**Pull request merged**
