### PR TITLE
Made Navbar Responsive among Mobile Devices

### PR DESCRIPTION
**Pull request by sabhisharma-ise**
As per the issue #215 

@akshitagupta15june 
Updated the files in the Project.
Added a Bootstrap Navbar - Responsive + Consistent among all devices.

Screenshots -

Desktop and wider screens -
| *Home page* |
image

| *Events page* |
image

| *Story page* |
image

| *Reward page* |
image

| *Rejuvenate page* |
image

Mobile screens - 
| *Home page* |
image

| *Events page* |
image

| *Story page* |
image

| *Reward page* |
image

| *Rejuvenate page* |
image

The other pages which are Meditation, Blog, and word are already responsive and good.

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Good Work.

Pls merge @akshitagupta15june and tag it level3

**Comment by akshitagupta15june** [comment]
resolve conflicts please

**Comment by sabhisharma-ise** [comment]
@akshitagupta15june Conflict Resolving is a Maintainer's responsibility. I don't have the access to do it.

**Comment by sabhisharma-ise** [comment]
@akshitagupta15june The conflicts should be resolve now, As the other person who also made a branch for Navbar Responsiveness has now deleted his branch. So, You can open this PR and check if it's fine now!

**Comment by akshitagupta15june** [comment]
conflicts are happening because your branch codebase is not updated with recent changes

**Comment by akshitagupta15june** [comment]
can u update your codebase? with recent changes

**Comment by sabhisharma-ise** [comment]
@akshitagupta15june 
Thank you for merging it😊

**Comment by Rakesh9100** [comment]
@akshitagupta15june Removing the tags as this PR is closed

**Pull request closed without merging**
