### PR TITLE
Fixes issue #1063

### PR DESCRIPTION
**Pull request by rayarka26**
Improved the divines activity page

### CODE REVIEW

**Comment by rayarka26** [comment]
Screenshot (177)
Screenshot (179)
Screenshot (180)

**Comment by rayarka26** [comment]
Fixes issue #1063

**Comment by rayarka26** [comment]
https://github.com/akshitagupta15june/Moksh/assets/74251803/417fafc8-65f3-47ce-97f2-acbe1c2a47b0

**Review by akshitagupta15june — APPROVED** [review]
Nice work 👍

**Pull request merged**
