### PR TITLE
fix: footer of pomodoro page

### PR DESCRIPTION
**Pull request by Viveksati5143**
Closes: #1199 #1201 #1205 
image
image
@akshitagupta15june done.

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Sign Up For Our Newsletter: is not visible in footer? @Viveksati5143

**Comment by Viveksati5143** [comment]
image
done @akshitagupta15june

**Review by Viveksati5143 — COMMENTED** [review]
pomodoro description text is also the same as it was.

**Comment by akshitagupta15june** [comment]
cool! Thanks

**Pull request merged**
