### PR TITLE
Issue #210 : Added styling to the scrollbar

### PR DESCRIPTION
**Pull request by harshita-kaushik2**
### Features : 
- Added styling to the scrollbar across all pages of the website.
- Colour coding as per the theme of the website.
- Additional functionality of colour change on hover.

Attaching a sample video of the functionality below:

https://github.com/akshitagupta15june/Moksh/assets/112249538/e039833d-6ad6-4ddf-82d9-300b130b63ab

Thank You :)

### CODE REVIEW

**Comment by harshita-kaushik2** [comment]
Hey @akshitagupta15june 
Sorry but I could not understand what you implied with fetch and merge.

**Comment by ankitjt** [comment]
@harshita-kaushik2 please do a new fetch request and update your local repository with new changes, the homepage was updated and you can see the changes.

**Comment by ankitjt** [comment]
I still see that you have not updated your brach with the latest changes, pl do that .

**Comment by harshita-kaushik2** [comment]
Hopefully, I have done what you instructed me to... 
For reviewing the functioning, you could look at the sample video attached in the PR above. 
Thank You !

**Review by akshitagupta15june — APPROVED** [review]
good work!!

**Pull request merged**
