### PR TITLE
Fixed blinking issue and Frontend redesign

### PR DESCRIPTION
**Pull request by Nishitbaria**
Fixes Issue: #945 
I have made the following changes in this pull request:

1. Fixed the page linking issue by redefining the `startTime` function in the frontend code. The new `startTime` function uses the `toLocaleTimeString` method to display the current time in the desired format. Additionally, I have added the `requestAnimationFrame` method to ensure smooth and efficient updating of the time display.

New `startTime` function:
```javascript
function startTime() {
  var today = new Date();
  var time = today.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit', hour12: true });

  document.getElementById('display').innerHTML = time;

  requestAnimationFrame(startTime);
}

startTime();
```

2.Redesigned the frontend to improve the layout and alignment of the cards in the card-container. I added the justify-center class to the card-container div to align cards.

Please review and merge this pull request. It addresses the issues mentioned and enhances the frontend design. Thank you!

### before
image

### after:(my work)
image

image
image
@akshitagupta15june ,please review my pull requesta and assign me level for my work

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@akshitagupta15june ,please review my pull request

**Comment by akshitagupta15june** [comment]
Hey please remove the three cards as they are not required here, I will add new section for it just shlok generator and footer

**Comment by akshitagupta15june** [comment]
Also the footer is changed please update your codebase

**Comment by Nishitbaria** [comment]
@akshitagupta15june ,i am updating asap.

**Comment by akshitagupta15june** [comment]
can u add updated screenshot, how the page looks and is it reponsive?

**Comment by Nishitbaria** [comment]
image
image
And it is not responsive,but i can make it responsive with tailwind css,i can create a isuue for that and why you closed issue before merging my pull request?

**Comment by Nishitbaria** [comment]
@akshitagupta15june ,please review changes and merge my pull request

**Review by akshitagupta15june — APPROVED** [review]
Good work!

**Comment by akshitagupta15june** [comment]
yes you can create issue regarding fixing the responsiveness

**Comment by Nishitbaria** [comment]
> yes you can create issue regarding fixing the responsiveness

Sure

**Comment by Nishitbaria** [comment]
Hey @akshitagupta15june , I created an issue for making a responsive  shlok_page web page. Could you please assign me the issue? I have made an issue here: https://github.com/akshitagupta15june/Moksh/issues/1074

**Pull request merged**
