### PR TITLE
Improved folder structure

### LINKED ISSUE #26: Improve folder structure
So i think we should create different folders for different files like for javascript we can create js folder for css files we can create css or style folder !!

### PR DESCRIPTION
**Pull request by Niravprajapati1**
closes #26

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
as most of the files are updated so please update your code with the current one and also please provide a short screensshare video of the website for me to check everything is working fine

**Comment by Niravprajapati1** [comment]
https://user-images.githubusercontent.com/83688779/232174865-8ff268b1-89a9-4fa9-af03-66df14444d12.mp4

**Review by akshitagupta15june — APPROVED** [review]
good work! @Niravprajapati1

**Comment by akshitagupta15june** [comment]
can u resolve the conflicts! so that i can merge your pr

**Comment by Niravprajapati1** [comment]
Screenshot_2023-04-16-06-45-40-65

**Comment by akshitagupta15june** [comment]
@Niravprajapati1 i think this issue can be handled by me you can look for other issues to work on, i will assign you

**Comment by Niravprajapati1** [comment]
Sure 😃

**Pull request closed without merging**
