### PR TITLE
Krishna's quotes with soothing background music

### PR DESCRIPTION
**Pull request by ManaswiKasiraju**
Here I have created a navigation where in as we go page by page we get to read different quotes with a repetitive music and gif background.
krishna_quote

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
hey you were not assigned an issue for this, also this is not required in website

**Comment by ManaswiKasiraju** [comment]
#227 is my issue number. And you assigned it to me. 
pic1
pic2

**Comment by akshitagupta15june** [comment]
Hey! I think there was some misunderstanding
I assigned you this for adding soothing music in ar meditation

**Comment by akshitagupta15june** [comment]
Krishna quottes teaching is not required because already we have Gita shloks generator

**Comment by akshitagupta15june** [comment]
You can work on adding Krishna's soothing music on ar meditation page

**Comment by ManaswiKasiraju** [comment]
Okay, Thank you!

**Comment by ManaswiKasiraju** [comment]
Hey, but the AR meditation page already has music available.

**Pull request closed without merging**
