### PR TITLE
#issue80 solved

### PR DESCRIPTION
**Pull request by MOHDNEHALKHAN**
#80   add footer in read a shlok page 
@akshitagupta15june please review it

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Can u add a screenshot

**Comment by MOHDNEHALKHAN** [comment]
Motivation page
Check it.

**Review by akshitagupta15june — APPROVED** [review]
Awesome 👍

**Comment by MOHDNEHALKHAN** [comment]
Thank u so much for merging as this is my first open source contribution to public repository👍🏻

**Pull request merged**
