### PR TITLE
Fix issue #1310

### PR DESCRIPTION
**Pull request by Developer-Swati**
Added a fear blog

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
can u synk the code and update you codebase

**Comment by Developer-Swati** [comment]
ok

**Comment by akshitagupta15june** [comment]
Thanks

**Comment by akshitagupta15june** [comment]
hey @Developer-Swati page is distorted
image

**Comment by Developer-Swati** [comment]
I look into it

**Comment by Developer-Swati** [comment]
it is showing like this in my browser

my

**Pull request merged**
