### PR TITLE
Added Parallax to HeroSection

### PR DESCRIPTION
**Pull request by raghav1482**
Solve issue #1430 

Closes: #1430 

## Description

Added parallax to the hero section of homepage

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by raghav1482** [comment]
@akshitagupta15june  Kindly review my PR #1435 . Open to changes suggested.

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Please share screenshots to ur changes

**Comment by raghav1482** [comment]
https://drive.google.com/file/d/1M-F5k6WdugMb3xm52YN4loWg_XQ0g6Gp/view?usp=sharing

here is preview link

**Comment by raghav1482** [comment]
@akshitagupta15june  kindly review my PR #1435

**Comment by akshitagupta15june** [comment]
not able to see the changes, drive link not working

**Comment by raghav1482** [comment]
> not able to see the changes, drive link not working

Ma'am its a gif file , kindly download it through the link ...(i have checked the link)

**Comment by akshitagupta15june** [comment]
Great work!

**Pull request merged**
