### PR TITLE
Added favicon to all the html files

### LINKED ISSUE #70: Adding favicon to the website
Hey @akshitagupta15june I would like to  add favicon to the website please assign this issue to me

### PR DESCRIPTION
**Pull request by mnik7044**
I have added favicon in all the HTML files.
Closes #70

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
please add screenshots

**Comment by mnik7044** [comment]
Screenshot 2023-04-21 175032
Screenshot 2023-04-21 175048
Screenshot 2023-04-21 175058
Screenshot 2023-04-21 175108
Screenshot 2023-04-21 175117
Screenshot 2023-04-21 175130
Screenshot 2023-04-21 175148

**Comment by mnik7044** [comment]
Hey @akshitagupta15june  to all the html files I have added the moksh logo as favicon I have uploaded the resulting screenshot

**Review by akshitagupta15june — APPROVED** [review]
good job!!

**Pull request merged**
