### PR TITLE
adding hover effect to the navbar

### PR DESCRIPTION
**Pull request by Aditi323**
Screenshot (142)
Screenshot (141)
Screenshot (140)
Screenshot (139)
Hey @Rakesh9100  this solves issue #167 
changed the text type and font size with hovering colors
now the nav item does not  overlap with each other when the screen width is below 768px
Removed the arrow down icon so that the drop-down items  are automatically visible when we hover above it and this makes the navbar look more appealing

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls provide the screenshots of your changes @Aditi323

**Comment by Aditi323** [comment]
> Pls provide the screenshots of your changes @Aditi323

done

**Comment by akshitagupta15june** [comment]
please mention Power of Knowledge Blogs instead of mental wellness check the https://akshitagupta15june.github.io/Moksh/index.html

**Comment by Aditi323** [comment]
> please mention Power of Knowledge Blogs instead of mental wellness check the https://akshitagupta15june.github.io/Moksh/index.html

 done

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
good work!!

**Pull request merged**
