### PR TITLE
Back Button added in all blogs

### PR DESCRIPTION
**Pull request by rayarka26**
Fixes Issue #1014

### CODE REVIEW

**Comment by rayarka26** [comment]
Screenshot (164)

**Comment by rayarka26** [comment]
Added back button in all the blogs redirect to blog.html

**Comment by akshitagupta15june** [comment]
can you keep the colour of button blue

**Comment by rayarka26** [comment]
ok i will change it

**Comment by rayarka26** [comment]
Screenshot (165)

**Comment by rayarka26** [comment]
@akshitagupta15june  please check. You have closed the issue

**Comment by rayarka26** [comment]
please check and merge

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
Good work!

**Pull request merged**
