### PR TITLE
cards dynamic carousel

### PR DESCRIPTION
**Pull request by karthiknadar1204**
Have made the entire section dynamic so now we can add en number of stories, it would dynamically be rendered into cards and placed appropriately .

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
Please consider this under gssoc'23

**Comment by karthiknadar1204** [comment]
😌

**Review by akshitagupta15june — APPROVED** [review]
Good work!

**Comment by akshitagupta15june** [comment]
please update your codebase

**Comment by karthiknadar1204** [comment]
@akshitagupta15june Done

**Pull request merged**
