### PR TITLE
Added Contact Page

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Hello @akshitagupta15june ,
I have added the `Contact Page` 

## Screenshot - 
Screenshot from 2023-06-22 12-45-13

### It is ready to merge.

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
mention the issue number, were u assigned?

**Comment by SyedImtiyaz-1** [comment]
It's Issue No. #858

**Comment by akshitagupta15june** [comment]
hey u were not assigned this issue so I am closing this pr
I have already said without being assigned please don't create pr

**Comment by SyedImtiyaz-1** [comment]
Okay

**Pull request closed without merging**
