### PR TITLE
Improved footer of divine activities page

### PR DESCRIPTION
**Pull request by PatakiGergo**
Improved footer of divine activities page

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Please add a screenshot

**Comment by PatakiGergo** [comment]
image

**Comment by akshitagupta15june** [comment]
Please try to keep the footer same as index page

**Comment by PatakiGergo** [comment]
image
Like this?

**Comment by akshitagupta15june** [comment]
Can u remove quick link and home

**Comment by PatakiGergo** [comment]
image
Is it okay like this?

**Comment by akshitagupta15june** [comment]
yes

**Review by akshitagupta15june — APPROVED** [review]
Good job!!

**Pull request merged**
