### PR TITLE
New Background image for index.html

### LINKED ISSUE #872: [FEATURE REQUEST]
https://akshitagupta15june.github.io/Moksh/
Need a good background picture for index.html, it should be bright and keep theme on mind also share the pictures here before creating pr to get it approved

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
Screenshot 2023-06-26 at 15 13 37

Closes #872 

Updated code base by using git pull. 
Updated the background image of index.html page.

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
please change the text colour to white also om should be little down as it is merging with navbar

**Comment by Vidip-Ghosh** [comment]
> please change the text colour to white also om should be little down as it is merging with navbar

Okay alright

**Comment by akshitagupta15june** [comment]
add a screenshot please with new changes

**Comment by Vidip-Ghosh** [comment]
Screenshot 2023-06-27 at 21 20 37

**Review by akshitagupta15june — APPROVED** [review]
Great work!!

**Pull request merged**
