### PR TITLE
Improved Responsiveness of all divine exercises page(#320)

### PR DESCRIPTION
**Pull request by rishitachail**
@akshitagupta15june @karthiknadar1204  (issue #320 )
I made changes to story.html and story.css to make the page responsive in all views. Kindly review and merge it.

https://github.com/akshitagupta15june/Moksh/assets/108628119/7d23f42f-bbcd-4f8f-8c86-5398829d9885

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
Please put the issue link in the description as it would be easier for us to navigate

**Comment by rishitachail** [comment]
> Please put the issue link in the description as it would be easier for us to navigate

@karthiknadar1204 Done

**Comment by ankitjt** [comment]
image

See the highlighted section , it send some of your content is bleeding out which should not happen. 

Look into it.

**Comment by akshitagupta15june** [comment]
please create a new pr for same after updating ur code

**Pull request closed without merging**
