### PR TITLE
hide the text 

### PR DESCRIPTION
**Pull request by dheeraj1129**
hiding the Google translate text and image.

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
Please share the screenshots of the change you have implemented

**Comment by dheeraj1129** [comment]
Screenshot (4)

**Comment by Rakesh9100** [comment]
It seems like two blue abckgrounds are being overlapped in navbar which is not looking good. Pls correct it and also provide the issue number this PR closes.

**Comment by Rakesh9100** [comment]
It seems like two blue backgrounds are being overlapped in navbar which is not looking good. Pls correct it and also provide the issue number this PR closes.

**Comment by akshitagupta15june** [comment]
share the issue number please

**Comment by akshitagupta15june** [comment]
closing this as received no response

**Pull request closed without merging**
