### PR TITLE
Added animations to the images.

### PR DESCRIPTION
**Pull request by Sathvik902**
Added some cool animations to the images on the home page.

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
conflicting files
please update your code base , do a fetch and merge

**Comment by Sathvik902** [comment]
Sure!

**Comment by Sathvik902** [comment]
Will do it today

**Comment by akshitagupta15june** [comment]
do a fetch and merge please

**Comment by akshitagupta15june** [comment]
do it please

**Pull request closed without merging**
