### PR TITLE
Added Dark Mode Functionality

### PR DESCRIPTION
**Pull request by mud1tx**
Added Dark Mode Functionality.

The mode chosen by the user does not change even if the page is refreshed as the theme is store in Localhost.

Also change the file structure based on HTML, CSS, JS, and Themes to make it easy to browse the files.

checked each and everything.

#84

### CODE REVIEW

**Comment by mud1tx** [comment]
@akshitagupta15june I just read the issue now that I have to create dark mode only for the index page. By mistake, I created the dark mode feature for all the pages😅

**Comment by akshitagupta15june** [comment]
No issue its beeter you added for all pages , can you update your branch with current code so as to resolve all conflicts

**Comment by mud1tx** [comment]
@akshitagupta15june Please see the code and merge it I have remove all the conflicts.

**Review by akshitagupta15june — APPROVED** [review]
After merging the site was distorted so reverted your changes

**Comment by akshitagupta15june** [comment]
did u create folders for diffrent html css and js files

**Comment by mud1tx** [comment]
@akshitagupta15june I don't know why the site crashed as I checked everything on local storage it was working.

**Pull request merged**
