### PR TITLE
Added Fear blog

### PR DESCRIPTION
**Pull request by Developer-Swati**
Added a blog on topic  fear 

img2

img1

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
fear image should be like this 
image

**Comment by Developer-Swati** [comment]
Ok

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Have you made the changes?

**Comment by Developer-Swati** [comment]
Yeah, I am creating pull request in just 30 min

**Comment by Developer-Swati** [comment]
Is it ok?

pr2
pr1

**Comment by akshitagupta15june** [comment]
Looks nice

**Comment by akshitagupta15june** [comment]
Thankyou so much @Developer-Swati

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
hey the index file is not present can u see to it?

**Comment by akshitagupta15june** [comment]
I can't see the the blog in the blog.html page

**Comment by Developer-Swati** [comment]
Yeah because I just asked for your approval for the image but not commited yet

**Comment by akshitagupta15june** [comment]
Oh my bad
You can create pr again

**Pull request merged**
