### PR TITLE
footer is added to AR-Mediate Page [GSSOC'23] #662

### PR DESCRIPTION
**Pull request by shivaniyuvrajyadav**
#662 
before adding footer 
image

after  adding footer
image

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
add the same footer as index.html

**Comment by ankitjt** [comment]
can you share the screenshots here

**Comment by ankitjt** [comment]
@shivaniyuvrajyadav have you made the changes?

**Comment by ankitjt** [comment]
I did a fresh pull of the changes and I don't see these images, just a do fresh fetch and see

**Comment by shivaniyuvrajyadav** [comment]
@akshitagupta15june @ankitjt Please check I have done all the changes. now it is working fine.

**Comment by shivaniyuvrajyadav** [comment]
I have updated the commonscript.js file according to the new changes.

**Comment by shivaniyuvrajyadav** [comment]
@akshitagupta15june  please review my PR.

**Pull request merged**
