### PR TITLE
Fixed Navbar Of Pomodoro Page

### PR DESCRIPTION
**Pull request by Sch476**
Fixed the issue #1156 .

Video : 

https://github.com/akshitagupta15june/Moksh/assets/127319225/8269d7a6-eeb6-43f2-a65a-2d7757e79413

### CODE REVIEW

**Review by Viveksati5143 — COMMENTED** [review]
Screenshot of the changes?

**Comment by akshitagupta15june** [comment]
You just need to change the background of navbar while scrolling
What changes you have made in scroll.js add a screenshot too

**Comment by Sch476** [comment]
Added a ScreenCase

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Ok i got it, also please synk changes with current codebase also can u see what changes you have made with scroll.js? in files changed

**Pull request closed without merging**
