### PR TITLE
Added the google translation box

### PR DESCRIPTION
**Pull request by Developer-Swati**
Actually , I have changed the div id of google-translate-element to google-element and added some style to it . Also changed the script tag. But because there was problem while creating pull request so I have to clone twice and previously I made changes to the file that showed permission denied while pushing so, I have to clone again and change . Then I just copied my previously corrected code to the new one so it is not showing the deleted lines .

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Please add a screenshot

**Comment by Developer-Swati** [comment]
Ok sure

**Comment by Developer-Swati** [comment]
Screenshots:
 
english


malyalm


hindi

**Review by akshitagupta15june — APPROVED** [review]
Good work

**Pull request merged**
