### PR TITLE
Updated README.md file by adding some changes

### PR DESCRIPTION
**Pull request by bhavyasingh75**

### CODE REVIEW

**Review by bhavyasingh75 — COMMENTED** [review]
I have added some lines and updated some of the content. Please feel free to give your feedback and I'll look into it.

**Comment by Rakesh9100** [comment]
Are you GSSoC contributor? Any issue assigned to you? Pls look to this @akshitagupta15june

**Comment by akshitagupta15june** [comment]
share the issue number which u were assigned

**Comment by bhavyasingh75** [comment]
Yes. I am a GSSoC contributor. My discord ID is Bhavya | Contributor aka
niks03#8203.
The issue was related to updating the README file. You could have seen the
changes.


bsingh

**Pull request closed without merging**
