### PR TITLE
NavBar modified

### PR DESCRIPTION
**Pull request by PVBharadwaj**
Navbar was modified. @akshitagupta15june Please review this PR to merge.

### CODE REVIEW

**Comment by PVBharadwaj** [comment]
This PR will close the issue #544

**Comment by PVBharadwaj** [comment]
I am a GSSoC'23 contributor.

**Comment by Rakesh9100** [comment]
Do provide the screenshot of your changes @PVBharadwaj

**Comment by PVBharadwaj** [comment]
> Do provide the screenshot of your changes @PVBharadwaj

Screenshot
Please find the screenshot of the page here. Previously contents were aligned to the top, not at the centre.

**Pull request closed without merging**
