### PR TITLE
 I adjusted margin of moksh logo in story.html

### PR DESCRIPTION
**Pull request by dipakja**
In line #160 i have made changes

### CODE REVIEW

**Comment by dipakja** [comment]
Moksh logo in Divine_page/story.html

**Comment by karthiknadar1204** [comment]
@dipakja Please share the screenshots for the changes you have applied

**Comment by dipakja** [comment]
image

**Comment by dipakja** [comment]
This is an after change

**Comment by dipakja** [comment]
This is before change screenshot, you can see the logo of Moksh , it is  slightly  down. So i adjust it

**Comment by dipakja** [comment]
Moksh_before_change

**Comment by dipakja** [comment]
Sir, this is my first open source contribution and I think I didn't make that many changes or important changes. 
I thought this is a good to start.

**Comment by akshitagupta15june** [comment]
can u please synk your current code because it is creating conflict

**Pull request closed without merging**
