### PR TITLE
Added background in Pomodoro page

### PR DESCRIPTION
**Pull request by Developer-Swati**
Background same as Iskcon page has been added to the Pomodoro page

pomobg

### CODE REVIEW

**Comment by Developer-Swati** [comment]
What to do to pass all checks ? Should I have to create pull request again @akshitagupta15june ?

**Review by Viveksati5143 — APPROVED** [review]

**Comment by Developer-Swati** [comment]
@Viveksati5143  how to pass all these above changes? Will it create any problem in merging this PR? Any suggestions?

Thanks

**Review by akshitagupta15june — APPROVED** [review]
Thanks

**Comment by Developer-Swati** [comment]
> Thanks
You're welcome @akshitagupta15june

**Pull request merged**
