### PR TITLE
Page now responsive after click on read a shlok #1535

### PR DESCRIPTION
**Pull request by kapilG0**
## Related Issue

Closes: #1535 

## Description

Page is responsive for each device after click on read a shlok 

## Checklist 

- [ ] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]
Please add a video or screenshot of showing changes you have made

**Comment by kapilG0** [comment]
> Please add a video or screenshot of showing changes you have made

Hello @akshitagupta15june I am adding two images . I made read a shlok page responsive in that . Please check 
image
image

**Comment by SandeepKumar193** [comment]
I would like to work on this project pls approved my pull request

**Comment by kapilG0** [comment]
Hello @akshitagupta15june i attached screenshot for this please check above

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
Please fetch and merge to resolve conflicts

**Comment by kapilG0** [comment]
Hello @akshitagupta15june i have resolved conflicts please check

**Pull request merged**
