### PR TITLE
{GSSoC'23} Bug fix of image formats issue#1034

### PR DESCRIPTION
**Pull request by Daksh-Goel12**
I changed the image formats that were causing problems. I hope this solves the problem @akshitagupta15june

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]
Thanks! but stay in loop as this problem was not in any of my browsers but 3-4 contributors were facing this, so after merging it i will ask them if it fine at their end

**Comment by akshitagupta15june** [comment]
can u also pull the changes as some merge conflicts are present, update your codebase

**Comment by Daksh-Goel12** [comment]
Actually, I dont know how to resolve conflicts. Can you guide me ?

**Comment by akshitagupta15june** [comment]
Hey you just have to fetch and merge as there were some changes made to repo before you created the pr, so best practice is to always do a git pull to merge those recent changes otherwise they might create conflicts.
Here you just need to do a git pull

**Comment by Daksh-Goel12** [comment]
I think. its done ?

**Comment by akshitagupta15june** [comment]
Yes thankyou

**Comment by Daksh-Goel12** [comment]
Thank you to you too. If there is any other issue. please let me know I will be happy to contribute.

**Pull request merged**
