### PR TITLE
Update css of reward.html 

### PR DESCRIPTION
**Pull request by Akshatchaube01**
fixes issue : #1373

### CODE REVIEW

**Review by Viveksati5143 — COMMENTED** [review]
Can you share ss after change?

**Comment by Akshatchaube01** [comment]
@Viveksati5143 attached with the issue, please check #1373

**Comment by akshitagupta15june** [comment]
add a ss

**Comment by Akshatchaube01** [comment]
Before change :
Screenshot (1002)
After change : 
Screenshot (1003)

**Pull request merged**
