### PR TITLE
Added home.html and home.css

### PR DESCRIPTION
**Pull request by shivani-tripurari**
Changed the layout , background ,buttons in home and about section.

### CODE REVIEW

**Comment by shivani-tripurari** [comment]
Changes needed in the navbar.

**Comment by ankitjt** [comment]
Can you share screenshots ( desktop and mobile )?

**Comment by shivani-tripurari** [comment]
Screenshot (4)
Screenshot (3)
These are the pictures of about section

**Comment by shivani-tripurari** [comment]
I'll change the spacing between logo and the Moksh text

**Comment by akshitagupta15june** [comment]
hey! this colour is not preferred

**Comment by shivani-tripurari** [comment]
okay!

**Comment by shivani-tripurari** [comment]
> hey! this colour is not preferred

but is the layout okay?

**Comment by akshitagupta15june** [comment]
hey the layout i want it should be what initial is but i suggest you to keep the colour same and and u can work on the about and features section and suggest some ui in discord channel of moksh

**Comment by akshitagupta15june** [comment]
please add screenshots of your changes

**Comment by shivani-tripurari** [comment]
> please add screenshots of your changes

Hey Akshita I'll share you the screenshots of the designs till Friday on the discord server as I'm having exams

**Comment by shivani-tripurari** [comment]
Can you please specify again about the color of the website?

**Comment by rohan-kulkarni-25** [comment]
Hey @akshitagupta15june 
You can simply add a theme in this repository so everyone can use the color over there.

**Comment by akshitagupta15june** [comment]
UI has changed and now you can create issues for improvement.

**Pull request closed without merging**
