### PR TITLE
footer code modified in index.html and style.css

### PR DESCRIPTION
**Pull request by Mittalkashish**

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Resolve the conflicts and mention the issue number this PR closes @Mittalkashish

**Comment by Mittalkashish** [comment]
> Resolve the conflicts and mention the issue number this PR closes @Mittalkashish

ok

**Comment by Mittalkashish** [comment]
> Resolve the conflicts and mention the issue number this PR closes @Mittalkashish

 issue  number #433

**Comment by akshitagupta15june** [comment]
hey add a screenshot of footer

**Comment by Mittalkashish** [comment]
> hey add a screenshot of footer

ok

**Comment by Mittalkashish** [comment]
> hey add a screenshot of footer

Screenshot from 2023-05-27 22-31-12
Change the adrress and details as per your need

**Comment by Mittalkashish** [comment]
Mam , kindly pls check footer ss and merge pr

**Comment by akshitagupta15june** [comment]
hey this kind of footer is not required kindly check index.html

**Comment by akshitagupta15june** [comment]
company account resources are actuually not required

**Comment by Mittalkashish** [comment]
> hey this kind of footer is not required kindly check index.html


ok , shall i modify it ?

**Pull request closed without merging**
