### PR TITLE
improved the main page

### PR DESCRIPTION
**Pull request by karthiknadar1204**
Screenshot 2023-05-04 at 11 21 34 PM
Have moved the images around to make it look better

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
@akshitagupta15june This pr resolves issue #5

**Comment by akshitagupta15june** [comment]
Please check the layout in your local again because previously when I merged this 
All images were distorted

**Comment by karthiknadar1204** [comment]
It's still working fine,I think it's good to go!! @akshitagupta15june .

**Comment by karthiknadar1204** [comment]
@akshitagupta15june any update?

**Comment by karthiknadar1204** [comment]
Screenshot 2023-05-06 at 9 24 43 PM
Improved hover effect for navbar,instead of making the entire thing colored,this looks better with the color of out navbar, any suggestions @akshitagupta15june

**Comment by karthiknadar1204** [comment]
Screenshot 2023-05-06 at 9 33 11 PM

**Comment by karthiknadar1204** [comment]
Works perfectly fine on local machine @akshitagupta15june 
Resolves navbar hover improvement issue #117 , improves ui of main page #5 
Please Review
Thank you

**Review by akshitagupta15june — APPROVED** [review]

**Pull request merged**
