### PR TITLE
Fixed play-pause button positions | UI enhancement | Improved Responsiveness

### PR DESCRIPTION
**Pull request by Harsh-s0ni**
- fixed play-pause button positions
- added static images for audio cards
- made the site more responsive
- changed the presentation of QR codes and QR tagline
- UI enhancement
- added glassmorphism effect in audio cards

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls attach the output of the meditation page showing your changes here for easy check.

As I have checked locally, work on these changes:
1. Don't change the logo design and navbar look since logo should be same in every pages. Revert to previous one.
2. Lower the font size of text "Augmented Reality Meditation" a bit.

Rest is fine. Play/Pause button changes and static images are good. @Harsh-s0ni

**Comment by Rakesh9100** [comment]
Pls attach the output of the meditation page showing your changes here for easy check.

As I have checked locally, work on these changes:
1. Don't change the logo design and navbar look since logo should be same in every pages. Revert to previous one.
2. Lower the font size of text "Augmented Reality Meditation" a bit.

Rest is fine. Play/Pause button changes and static images are good. @Harsh-s0ni 

**Main thing to be noted that don't make changes to the main branch directly. Create a new branch for your changes.**

**Comment by Harsh-s0ni** [comment]
> Pls mention the issue number this PR closes in the description.
> 
> Attach the output of the meditation page showing your changes here for easy check.
> 
> As I have checked locally, work on these changes:
> 
>     1. Don't change the logo design and navbar look since logo should be same in every pages. Revert to previous one.
> 
>     2. Lower the font size of text "Augmented Reality Meditation" a bit.
> 
>     3. The every links of the `FEATURES` tab is not redirecting to the respective page.
> 
> 
> Rest is fine. Play/Pause button changes and static images are good. @Harsh-s0ni
> 
> **Main thing to be noted that don't make changes to the main branch directly. Create a new branch for your changes.**

sir, kindly check the commonScript.js file 
it is modified 2 days ago by ankitjt which is the reason for the modifications in nav bar 
i have not done any modifications in navbar

**Comment by ankitjt** [comment]
Have you checked the drop-down links recently they work , maybe do a fresh pull request and see ?

**Comment by Harsh-s0ni** [comment]
> Have you checked the drop-down links recently they work , maybe do a fresh pull request and see ?

done the modifications
the drop down links are working now

**Review by akshitagupta15june — APPROVED** [review]
awesome work!

**Pull request merged**
