### PR TITLE
Navbar done

### PR DESCRIPTION
**Pull request by rayarka26**
Issue Number #705

### CODE REVIEW

**Comment by rayarka26** [comment]
Screenshot (67)

**Comment by rayarka26** [comment]
#gssoc23

**Comment by ankitjt** [comment]
Keep the font of the links Montserrat

**Comment by rayarka26** [comment]
Screenshot (69)

**Comment by rayarka26** [comment]
Please check

**Comment by ankitjt** [comment]
pl check the down arrow on the features link , it should be facing downwards by default.

**Comment by rayarka26** [comment]
Screenshot (70)

**Comment by rayarka26** [comment]
Done please check

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
Great work!!

**Pull request merged**
