### PR TITLE
aligned the text and added margin

### PR DESCRIPTION
**Pull request by khandelwalaastha**
I have aligned the text in the footer and added a margin at the subscribe button 
ref #1271 
@khadar1020

### CODE REVIEW

**Comment by khandelwalaastha** [comment]
I have made the required changes have a look at it 
image

**Review by Viveksati5143 — COMMENTED** [review]
ss of change?

**Comment by khandelwalaastha** [comment]
pls add OSEN label to it

**Comment by khandelwalaastha** [comment]
pls add OSEN label to it

**Comment by khadar1020** [comment]
it was not assigned which is why I did not submit PR but no issues lets learn together @khandelwalaastha

**Comment by khadar1020** [comment]
It was not assigned that is why i did not submit PR but no issues @khandelwalaastha

**Pull request merged**
