### PR TITLE
Issue #1064 - Update reward.html to modify navbar and footer 

### PR DESCRIPTION
**Pull request by ArunMaramraj**
https://github.com/akshitagupta15june/Moksh/assets/121447227/f351a8fb-fbbd-431f-b3eb-77b2f1e90fab

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
please check is it responsive on all screen sizes?

**Comment by ArunMaramraj** [comment]
Hi @akshitagupta15june. I just checked and it doesn't work as intended on mobile. I'll get back to this

**Comment by ArunMaramraj** [comment]
@akshitagupta15june I attached the recording of the page on mobile now. It's responsive as is shown in video

https://github.com/akshitagupta15june/Moksh/assets/121447227/5aed3145-da20-4c8a-a85a-de1767e346f6

**Review by Viveksati5143 — APPROVED** [review]

**Review by akshitagupta15june — APPROVED** [review]
Good work 👍

**Pull request merged**
