### PR TITLE
fix : issue#564: "regarding Favicon"

### PR DESCRIPTION
**Pull request by visparmar**

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
@visparmar Please share the screen shot of the changes that you have applied and link the issue you resolved eg #issue_number

**Comment by visparmar** [comment]
link:- https://github.com/akshitagupta15june/Moksh/issues/564

**Comment by karthiknadar1204** [comment]
@visparmar Please wait for the issue to be assigned before opening the pr.

**Comment by Rakesh9100** [comment]
Issue not assigned, closing PR.

**Pull request closed without merging**
