### PR TITLE
changed the styling of timer on pomodoro break page

### PR DESCRIPTION
**Pull request by anushkaMohan**
This pull request solves issue - #1191

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Please add a screenshot of implementation and also show its responsiveness in mobile view

**Comment by anushkaMohan** [comment]
Here are some screenshots :
Screenshot (238)
Screenshot (239)
Screenshot (234)
Screenshot (233)
This is how it looks in mobile view : 
Screenshot (240)

**Comment by anushkaMohan** [comment]
Here are some screenshots : 
Screenshot (240)
Screenshot (239)
Screenshot (235)
Screenshot (233)
Here is how it looks in mobile view : 
Screenshot (240)

**Comment by akshitagupta15june** [comment]
please update the codebase to remove conflict also I see the start button is not visible in the mobile view, can u make the size of circle a little small to adjust

**Comment by anushkaMohan** [comment]
Here are some screenshots: 
Screenshot (237)
Screenshot (239)
Screenshot (235)
Screenshot (236)
Here is how it looks in mobile view : 
Screenshot (241)

**Comment by anushkaMohan** [comment]
> please update the codebase to remove conflict also I see the start button is not visible in the mobile view, can u make the size of circle a little small to adjust

okay. i will make the changes

**Comment by anushkaMohan** [comment]
This is how the timer looks in mobile view now:
Screenshot (242)

**Review by akshitagupta15june — APPROVED** [review]
Great work!

**Pull request merged**
