### PR TITLE
background updated

### PR DESCRIPTION
**Pull request by Harshu467**
#1166 Issue resolved, Please check and merge and give proper labels of gsoc and levels
image

### CODE REVIEW

**Comment by Harshu467** [comment]
@akshitagupta15june Please check and merge

**Review by Viveksati5143 — COMMENTED** [review]
Screenshots?

**Comment by akshitagupta15june** [comment]
Add a screenshot of your changes

**Comment by Harshu467** [comment]
> Screenshots?

Added

**Comment by Harshu467** [comment]
> Add a screenshot of your changes

Added

**Review by akshitagupta15june — APPROVED** [review]
Thanks

**Pull request merged**
