### PR TITLE
Improved UI of the feature cards [ Fixes: #6]

### PR DESCRIPTION
**Pull request by ritik48**
Hey @karthiknadar1204,
The feature cards with content seems to occupy a lot of space, so I have added expand and collapse animation on the cards, when they are hovered.

- Preview

https://github.com/akshitagupta15june/Moksh/assets/84488726/727d8fa0-1311-4f73-9370-587b97b93223

Please review my changes.

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Is this design perfectly working for small devices? @ritik48  If yes then can be merged, nice creation. @akshitagupta15june

**Comment by karthiknadar1204** [comment]
looks very nice @ritik48 ,could you just reconfirm if the expansion and collapse feature is working on smaller devices as well

**Comment by karthiknadar1204** [comment]
@ritik48 Could you also please consider changing the colour of the card heading from black to something lighter, it needs to match the tone of the website.
Rest looks good.

**Comment by ritik48** [comment]
@karthiknadar1204 yes it works on smaller devices as well when user click on cards.
moksh card color
Is this background color for the heading alright ?

**Comment by karthiknadar1204** [comment]
Yes, it looks amazing @ritik48 😃
Good to go.
@akshitagupta15june will merge it whenever she is available.
Thank you!!!

**Comment by ritik48** [comment]
Thanks @karthiknadar1204 , I am glad to have this chance of contributing to Moksh😄

**Comment by karthiknadar1204** [comment]
Looking forward to more contributions @ritik48 .

**Pull request merged**
