### PR TITLE
Styling header

### PR DESCRIPTION
**Pull request by UdhbhavSinghRana**
Screenshot from 2023-07-12 15-01-08
Screenshot from 2023-07-12 15-00-44
Screenshot from 2023-07-12 15-00-22
This is how the site is looking in different screen sizes issue number #1062

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Please mention issue number

**Review by Viveksati5143 — CHANGES_REQUESTED** [review]
Creating a issue first and then a pr is the right practice @UdhbhavSinghRana

**Comment by UdhbhavSinghRana** [comment]
> Please mention issue number

Sorry for the inconvenience now i have mentioned the issue number

**Comment by akshitagupta15june** [comment]
hey the navbar should be similar as the iskcon events page

**Comment by UdhbhavSinghRana** [comment]
> hey the navbar should be similar as the iskcon events page
ok i will change it

**Comment by UdhbhavSinghRana** [comment]
Screenshot from 2023-07-13 18-52-12
Screenshot from 2023-07-13 18-52-33
Screenshot from 2023-07-13 18-52-38
@akshitagupta15june  is this ok ?

**Review by akshitagupta15june — APPROVED** [review]
Great work!

**Pull request merged**
