### PR TITLE
Resolve the #280 issue 

### PR DESCRIPTION
**Pull request by harshita-india**
Improved the UI of footer section of the Iskcon event page and home page. And I have already tested

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls attach the screenshot of your changes here @harshita-india

**Comment by harshita-india** [comment]
home_footer

https://github.com/akshitagupta15june/Moksh/assets/69025470/dc1633c5-adf4-43c7-a2fc-4960425e6361

**Comment by harshita-india** [comment]
> Pls attach the screenshot of your changes here @harshita-india

Added please check

**Comment by harshita-india** [comment]
image
### updated footer

**Comment by harshita-india** [comment]
> please follow same colour scheme also add same footer as index.html

should i make same footer for all pages. I think i will look nice if all pages would have same footer and also user friendly

**Comment by harshita-india** [comment]
> I think adding navigation links in the footer seems a little redundant because we have an open navbar on all pages.
> 
> We are planning to add social media links and GitHub stats and for that we will be utilising footer section.
> 
> @akshitagupta15june Feedback ?

Ok , I should change the iscon event footer and remove quick links from it and make it same as home page footer

**Comment by harshita-india** [comment]
image
### removed the quick links page from the iscon and home page

**Comment by harshita-india** [comment]
> Reference

should i commit it??

**Comment by akshitagupta15june** [comment]
update your code also please keep the current index.html as it is the colours should be same

**Pull request closed without merging**
