### PR TITLE
google translation added

### LINKED ISSUE #1268: add google translation in Blog
in strength blog
image
in life blog
image
in words blog
image

To improve google translation in Cardinal Vices
image

I will change it like Depression & Suicide blog
image

### PR DESCRIPTION
**Pull request by RitiChandak**
Closes #1268 

Google translator added in all blog and 
image
image
image
image
image

### CODE REVIEW

**Comment by RitiChandak** [comment]
@akshitagupta15june please review the pr

**Comment by akshitagupta15june** [comment]
is the translation is responsive in all pages? because in mobile view sometimes it is floated to left

**Comment by RitiChandak** [comment]
yes i have made it responsive

**Comment by RitiChandak** [comment]
image
image

**Review by akshitagupta15june — APPROVED** [review]

**Comment by RitiChandak** [comment]
Thank you @akshitagupta15june

**Pull request merged**
