### PR TITLE
pomodoro page margin issue

### PR DESCRIPTION
**Pull request by LovishMalhotra**
Margin Issue in Pomodoro page resolved
Extra unwanted style and bootstrap classes were also removed.

Screenshot 2023-07-29 155617
Screenshot 2023-07-29 155225
Screenshot 2023-07-29 155052

### CODE REVIEW

**Comment by LovishMalhotra** [comment]
@akshitagupta Check this pull request and merge it with main branch

**Comment by akshitagupta15june** [comment]
I am not able to see whether it is responsive or not try to create a screencast video of showing whole page and please send it here

**Comment by LovishMalhotra** [comment]
It's responsive but I will send the video .

**Comment by akshitagupta15june** [comment]
yes please

**Comment by LovishMalhotra** [comment]
https://github.com/akshitagupta15june/Moksh/assets/90837700/c45dfd76-ce32-4ef3-a183-4f6bf9da2f9c

**Comment by LovishMalhotra** [comment]
check the screen recording it is responsive

**Review by akshitagupta15june — APPROVED** [review]

**Pull request merged**
