### PR TITLE
Added Fear blog

### PR DESCRIPTION
**Pull request by Developer-Swati**
Added finally

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]

**Comment by Developer-Swati** [comment]
You are welcome @akshitagupta15june

**Comment by akshitagupta15june** [comment]
The image is not commited ig.

**Comment by Developer-Swati** [comment]
I commited it but it is taking the previous one

**Comment by Developer-Swati** [comment]
It is not tracking the fear.html now . I am trying to add this file but it tracks the image
trace
untrace 
what to do @akshitagupta15june

**Comment by akshitagupta15june** [comment]
u can send the picture let me update it

**Comment by Developer-Swati** [comment]
Previously it was tracking and I added these file but it showed previously added image at your end

**Comment by Developer-Swati** [comment]
ok

**Comment by Developer-Swati** [comment]
fear2
I also have the .webp format but github does not support to it

**Pull request merged**
