### PR TITLE
fix: footer of pomodoro page

### PR DESCRIPTION
**Pull request by Viveksati5143**
Closes: #1199

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
Great! Thanks

**Comment by akshitagupta15june** [comment]
did u change the colour of pomodoro decscription text? please correct it
I am reverting this pr back
nothing is visible due to the grey colour
image

**Comment by Viveksati5143** [comment]
> did u change the colour of pomodoro decscription text? please correct it I am reverting this pr back nothing is visible due to the grey colour image

@akshitagupta15june this was a level 1 issue which was about matching tha footer with other page.
Now what else are you talking about? 
I guess you are matching someone else issue with me.

**Comment by Viveksati5143** [comment]
If you want I can create a new issue & pr for it but why would you revert this pr it was just for footer? @akshitagupta15june ?
Is there still any confusion?

**Comment by akshitagupta15june** [comment]
Yes but as you change the colour of text in footer it Changed the pomodoro description and content colour

**Comment by akshitagupta15june** [comment]
When a solving a problem it create another problem

**Comment by Viveksati5143** [comment]
ok sure

**Comment by Viveksati5143** [comment]
will fix it

**Pull request merged**
