### PR TITLE
Responsive Navbar among Mobile Devices

### PR DESCRIPTION
**Pull request by sabhisharma-ise**
As per the issue #215 

@akshitagupta15june 
Updated the files in the Project.
Added a Bootstrap Navbar -> Responsive + Consistent among all devices.

Screenshots -

Desktop and wider screens -
| *Home page* |
image

| *Events page* |
image

| *Story page* |
image

| *Reward page* |
image

| *Rejuvenate page* |
image

Mobile screens - 
| *Home page* |
image

| *Events page* |
image

| *Story page* |
image

| *Reward page* |
image

| *Rejuvenate page* |
image

The other pages which are Meditation, Blog, and word are already responsive and good.

### CODE REVIEW

**Comment by sabhisharma-ise** [comment]
Hey @akshitagupta15june Check this PR. It's having any merge conflicts now as I have created a new branch with all the new changes made in the project with sync

**Comment by Rakesh9100** [comment]
`index.html` is having conflict, pls resolve @sabhisharma-ise

**Comment by sabhisharma-ise** [comment]
@Rakesh9100 Hey, Resolved the merge conflicts.

**Comment by akshitagupta15june** [comment]
@sabhisharma-ise please check discord dm and will assign u seprate issues after restructuring

**Pull request closed without merging**
