### PR TITLE
Added logo and Navbar on one page

### PR DESCRIPTION
**Pull request by karthiknadar1204**
Added the New Logo on all the pages, the Ar vr page had a navbar missing, added a navbar to that page along with the new logo on the go.
Screenshot 2023-06-15 at 9 52 26 PM

Screenshot 2023-06-15 at 9 52 37 PM

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
I just tried making it circular but the text in the logo is barely visible if made circular

**Comment by karthiknadar1204** [comment]
Screenshot 2023-06-15 at 10 06 07 PM

@akshitagupta15june

**Comment by akshitagupta15june** [comment]
Oh ok no issues
I will talk to paulav to make the size big

**Comment by akshitagupta15june** [comment]
Thankyou for the great work

**Pull request merged**
