### PR TITLE
Update Readme functionality: Embed video, Graphical elements, Typos

### PR DESCRIPTION
**Pull request by Pratik-11**
### Updated Readme.md
- Removed and corrected Typos
- Added play video in Readme.md functionality
- Added extra graphical elements
- Enhanced the Readme file
- Fixed bugs from previous PR as requested

### CODE REVIEW

**Comment by Pratik-11** [comment]
Hi i have reviewed your previous comments and this is the new PR

**Comment by ankitjt** [comment]
Provide the issue number this pull request is for.

**Comment by Pratik-11** [comment]
its #703 here.

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
good work!!

**Pull request merged**
